// import test from "node:test";
// import assert from "node:assert/strict";
// import path from "node:path";
// import electron from "electron";

// const { app, BrowserWindow } = electron;

// console.log("app:", app);

// test("api generated by preload is accessible in renderer", async () => {
//   await app.whenReady();
//   const win = new BrowserWindow({
//     webPreferences: {
//       preload: path.join(__dirname, "..", "preload.js"),
//       contextIsolation: true,
//     },
//   });

//   await win.loadURL("data:text/html,<html><body></body></html>");

//   const result = await win.webContents.executeJavaScript(`
//     window.controllerAPI.createListing('testEvent', { testKey: 'testValue' }
//   `);

//   assert.deepEqual(result, { eventName: "testEvent", payload: { testKey: "testValue" } });
//   await win.close();
// });
